version: "3"

services:
  dnsanon:
    build: .
    container_name: dnsanon
    image: dnsanon
    tty: true
    volumes:
      - /home/wiperpr/projects/PPSASOP_WP3/nfdump-docker/raw:/mnt/raw
      - /home/wiperpr/projects/PPSASOP_WP3/iscxvpn2016/dns_complete:/mnt/export

volumes:
   raw:
   export:
