version: "3"

services:
  nfdump:
    build: .
    container_name: nfdump
    image: ubuntu:14.04
    tty: true

    volumes:
      - ./raw:/mnt/raw
      - ./export:/mnt/export

volumes:
   raw:
   export:
