version: "3"

services:
  dnsanon:
    build: .
    container_name: dnsanon
    image: fedora/dnsanon:latest
    tty: true
    volumes:
      - ./raw:/mnt/raw
      - ./dns:/mnt/export

volumes:
   raw:
   export:
