version: "3"

services:
  nfdump:
    build: .
    container_name: dnsanon
    image: fedora/dnsanon:latest
    tty: true

    volumes:
      - ./raw:/mnt/raw
      - ./export:/mnt/export

volumes:
   raw:
   export:
